---
# various networking configurations
# using systemd-networkd and systemd-resolved
# https://wiki.archlinux.org/index.php/Systemd-networkd

- name: create virtual bridge interface for external network
  copy:
    src: 01-extern0.netdev
    dest: /etc/systemd/network/01-extern0.netdev
    mode: '0644'
  notify: restart systemd-networkd
  when: network.external.bridged
  tags: configs

- name: bind external interface to bridge
  template:
    src: 02-extern0-bind.network.j2
    dest: /etc/systemd/network/02-extern0-bind.network
    mode: '0644'
  notify: restart systemd-networkd
  when: network.external.bridged
  tags: configs

- name: bridge external network
  copy:
    src: 03-extern0.network
    dest: /etc/systemd/network/03-extern0.network
    mode: '0644'
  notify: restart systemd-networkd
  when: network.external.bridged
  tags: configs

# internal network, only for router

- name: create virtual bridge interface for internal network
  copy:
    src: 11-intern0.netdev
    dest: /etc/systemd/network/11-intern0.netdev
    mode: '0644'
  notify: restart systemd-networkd
  when: network.router
  tags: configs

- name: bind internal interface to bridge
  template:
    src: 12-intern0-bind.network.j2
    dest: /etc/systemd/network/12-intern0-bind.network
    mode: '0644'
  notify: restart systemd-networkd
  when: network.router
  tags: configs

- name: bridge internal network
  template:
    src: 13-intern0.network.j2
    dest: /etc/systemd/network/13-intern0.network
    mode: '0644'
  notify: restart systemd-networkd
  when: network.router
  tags: configs

- name: enable ipforward
  copy:
    src: 30-ipforward.conf
    dest: /etc/sysctl.d/30-ipforward.conf
    mode: '0644'
  notify: load sysctl
  tags: configs

# enable services
- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
    enabled: true
  tags: configs

- name: create symbolic link for resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  tags: configs

- name: enable systemd-networkd
  service:
    name: systemd-networkd
    enabled: true
  tags: configs

- name: dns setups
  include: dns.yml
  tags: dns

- name: dhcp setups
  include: dhcp.yml
  tags: dhcp

- name: nftables setups
  include: nftables.yml
  tags: nftables

- name: multicast setups
  include: avahi.yml
  tags: avahi
  when: network.router
