---
- name: create nftables.conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
    validate: "nft -cf %s"

- name: enable nftables
  service:
    name: nftables
    enabled: yes
