---
- name: create nftables.conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
    validate: "nft -cf %s"
  tags: configs

- name: enable and restart nftables
  service:
    name: nftables
    enabled: true
    state: restarted
  tags: configs
