---

- name: install mariadb
  community.general.pacman:
    name: mariadb
    state: present
  tags: packages

- name: initialize mariadb
  command: "mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql"
  tags: configs

- name: enable and start mariadb
  service:
    name: mariadb
    state: started
    enabled: true
  tags: configs
