---
- name: install ansible and python-passlib
  community.general.pacman:
    name: 
      - ansible
      - python-passlib
    state: present

- name: install ansible-lint
  community.general.pacman:
    name:
      - ansible-lint
    state: present

- name: install ansible-lint dependency
  community.general.pacman:
    name:
      - yamllint
    extra_args: --asdeps
    state: present
