---
# add grub kernel parameters
- name: set kernel commandline
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    state: present
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ kernel.parameters }}"'
  when: kernel.parameters
  notify: rebuild grub
