---
- name: install base and base-devel packages
  community.general.pacman:
    name: 
      - base
      - base-devel
    state: present

- name: Install system monitoring related apps
  community.general.pacman:
    name:
      - sysstat
      - glances
      - htop
      - smartmontools
      - progress
    state: present

- name: install needed dependencies for monitoring-related apps
  community.general.pacman:
    name:
      - tk
      - lsof
      - strace
