---
- name: install base and base-devel packages
  community.general.pacman:
    name:
      - base
      - base-devel
    state: present

- name: Install system monitoring related apps
  community.general.pacman:
    name:
      - sysstat
      - glances
      - htop
      - smartmontools
      - progress
    state: present

- name: install needed dependencies for monitoring-related apps
  community.general.pacman:
    name:
      - tk
      - lsof
      - strace
    state: present
    extra_args: --asdeps

- name: install nftables
  community.general.pacman:
    name: nftables
    state: present

- name: install routers related apps
  community.general.pacman:
    name:
      - ntp
    state: present
  when: network.router

- include: configs.yml
