ansible_ssh_host: 10.147.20.253
network:
  router: true
  external:
    interface: enp1s7
    bridged: true
  internal:
    interface: enp1s10
    bridged: true
    address: 10.10.0.253
    netmask: 24
  dns:
    server: true
    master:
      zone: java281.lan
      reverse: 0.10.10.in-addr.arpa
      octet: 253
    forwarders:
      - 127.0.0.1 port 53000
      - ::1 port 53000
  dhcp:
    server: true
  lan:
    address: 10.10.0.0
    netmask: 24
    netmask2: 255.255.255.0
    range:
      start: 10.10.0.100
      end: 10.10.0.200
    router: 10.10.0.253

display:
  server: xorg
  driver: intel
  manager: lightdm
