ansible_ssh_host: 10.147.20.252
network:
  router: false
  external:
    interface: enp1s0
    bridged: true
  dns:
    server: true
    master:
      reverse: 10.0.10.in-addr.arpa
      octet: 252
    slave:
      zone: java281.lan
      master: 10.147.20.253
    forwarders:
      - 127.0.0.1 port 53000
      - ::1 port 53000
      - 10.147.20.253
  lan:
    address: 10.0.10.0
    netmask: 24
